### ISSUE TITLE
Bug when KML coordinates are separated by only \n

### ISSUE THREAD

**Issue by layman-development** [bsimser/GeoJSON.NET#3]
In class GeoJsonRootObject line 217:
`v = Regex.Replace(v, "\n", "");`  should be `v = Regex.Replace(v, "\n", " ");` where "\n" is replace by a one character string.  This was breaking on my KML as there was no longer any space between coordinate groups.

The error was "Input string was not in a correct format."

**Comment by JamesKosher** [comment]
`at BilSimser.GeoJson.GeoJsonConvert.Convert(String input) in G:\\git\\BaumRealtyGroup\\Projects\\baumrealty.com Website\\BilSimser.GeoJson\\GeoJsonConvert.cs:line 29
   at BaumRealty.Web.Controllers.api.GeoJsonController.Index(String polygon, String type) in G:\\git\\BaumRealtyGroup\\Projects\\baumrealty.com Website\\BaumRealty.Web\\Controllers\\api\\GeoJsonController.cs:line 34
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.
Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
`
